# docker-compose.yml
version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://api.openbrewerydb.org/v1/breweries"
    ports:
      - "5173:80"
